FROM ubuntu:latest

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && \
    apt upgrade -y

RUN apt install -y curl git zsh make && \
    curl -fsSL https://crystal-lang.org/install.sh | bash

RUN shard install

RUN apt clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*