version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.crystal
    container_name: crystal-env
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ..:/workspace
      - ~/.gitconfig:/root/.gitconfig
      - ~/.ssh:/root/.ssh
    command: sleep infinity
